name: build

on: [push]

jobs:
  build-cinema-server:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: configure
      run: | 
        mkdir build
        cd build
        cmake ..
        
    - name: build cinemad
      run: | 
        cd build/cinema-server/cinemad
        make
        
    - name: build cinemactl
      run: | 
        cd build/cinema-server/cinemactl
        make
         
  build-cinema-client:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2  
      
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.2.0    
        
    - name: configure
      run: | 
        mkdir build
        cd build
        cmake -G "NMake Makefiles" ..
        
    - name: build
      run: | 
        cd build/cinema-client
        nmake
