name: build

on: [push]

jobs:
  build-cinema-server:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build cinemad
      run: cd build && cmake --build cinema-server/cinemad
    - name: build cinemactl
      run: cd build && cmake --build cinema-server/cinemactl

  build-cinema-client:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cd build && cmake --build cinema-client
  
