name: build

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build-server:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build cinemad
      if: matrix.os == 'ubuntu-latest'
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}  --target cinemad

    - name: Build cinemactl
      if: matrix.os == 'ubuntu-latest'
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}  --target cinemactl

    - name: Build client
      if: matrix.os == 'windows-latest'
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}  --target client

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
      
