name: build

on: [push]

jobs:
  build-cinema-server:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure SonarScanner
      run: | 
        export SONAR_SCANNER_VERSION=4.2.0.1873
        export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
        curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip 
        unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
        export PATH=$SONAR_SCANNER_HOME/bin:$PATH
        export SONAR_SCANNER_OPTS="-server"
        curl --create-dirs -sSLo $HOME/.sonar/build-wrapper-linux-x86.zip https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
        unzip -o $HOME/.sonar/build-wrapper-linux-x86.zip -d $HOME/.sonar/
        export PATH=$HOME/.sonar/build-wrapper-linux-x86:$PATH
    - name: configure
      run: | 
        mkdir build
        cd build
        cmake ..
    - name: build cinemad
      run: cd build && cmake --build cinema-server/cinemad
    - name: build cinemactl
      run: cd build && cmake --build cinema-server/cinemactl

  build-cinema-client:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cd build && cmake --build cinema-client
  
